name: deploy
on:
  push:

env:
  IMAGE_DOCKERHUB: blackdark93/nordvpn
  IMAGE_GHCR: blackdark/nordvpn

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch name
        id: git
        run: |
          NAME=$(echo ${GITHUB_REF} | sed -e "s/.*\///g")
          echo name=${NAME}  ref=${GITHUB_REF}
          echo "::set-output name=name::${NAME}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64,arm,386

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_NAME || github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ env.IMAGE_DOCKERHUB }}:${{ steps.git.outputs.name }}
            ghcr.io/${{ env.IMAGE_GHCR }}:${{ steps.git.outputs.name }}

      - name: Push latest
        uses: docker/build-push-action@v2
        if: steps.git.outputs.name == 'master'
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ env.IMAGE_DOCKERHUB }}:latest
            ghcr.io/${{ env.IMAGE_GHCR }}:latest

      # - name: Update repo description
      #   uses: peter-evans/dockerhub-description@v2
      #   if: steps.git.outputs.name == 'master'
      #   with:
      #     username: ${{ secrets.DOCKERHUB_NAME || github.repository_owner }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     repository: ${{ github.repository }}
